const types = {
  SAVE_PARAMS: "SAVE_PARAMS",
  SAVE_ARRAY: "SAVE_ARRAY",
  SAVE_ROWS: "SAVE_ROWS",
  SAVE_CELLS: "SAVE_CELLS",

  REMOVE_ROW: "REMOVE_ROW",
  ADD_ROW: "ADD_ROW",

  INCREASE: "INCREASE",
  ILLUMINATE: "ILLUMINATE"
};

export default types;
